export const ANIME_LIST_REQUEST = 'ANIME_LIST_REQUEST';
export const ANIME_LIST_SUCCESS = 'ANIME_LIST_SUCCESS';
export const ANIME_LIST_FAIL = 'ANIME_LIST_FAIL';

export const ANIME_DETAILS_REQUEST = 'ANIME_DETAILS_REQUEST';
export const ANIME_DETAILS_SUCCESS = 'ANIME_DETAILS_SUCCESS';
export const ANIME_DETAILS_FAIL = 'ANIME_DETAILS_FAIL';

export const ANIME_DELETE_REQUEST = 'ANIME_DELETE_REQUEST';
export const ANIME_DELETE_SUCCESS = 'ANIME_DELETE_SUCCESS';
export const ANIME_DELETE_FAIL = 'ANIME_DELETE_FAIL';

export const ANIME_CREATE_REQUEST = 'ANIME_CREATE_REQUEST';
export const ANIME_CREATE_SUCCESS = 'ANIME_CREATE_SUCCESS';
export const ANIME_CREATE_FAIL = 'ANIME_CREATE_FAIL';
export const ANIME_CREATE_RESET = 'ANIME_CREATE_RESET';

export const ANIME_UPDATE_REQUEST = 'ANIME_UPDATE_REQUEST';
export const ANIME_UPDATE_SUCCESS = 'ANIME_UPDATE_SUCCESS';
export const ANIME_UPDATE_FAIL = 'ANIME_UPDATE_FAIL';
export const ANIME_UPDATE_RESET = 'ANIME_UPDATE_RESET';

export const ANIME_CREATE_REVIEW_REQUEST = 'ANIME_CREATE_REVIEW_REQUEST';
export const ANIME_CREATE_REVIEW_SUCCESS = 'ANIME_CREATE_REVIEW_SUCCESS';
export const ANIME_CREATE_REVIEW_FAIL = 'ANIME_CREATE_REVIEW_FAIL';
export const ANIME_CREATE_REVIEW_RESET = 'ANIME_CREATE_REVIEW_RESET';

export const ANIME_TOP_REQUEST = 'ANIME_TOP_REQUEST';
export const ANIME_TOP_SUCCESS = 'ANIME_TOP_SUCCESS';
export const ANIME_TOP_FAIL = 'ANIME_TOP_FAIL';
