export const TOP_ANIME_LIST_REQUEST = 'TOP_ANIME_LIST_REQUEST';
export const TOP_ANIME_LIST_SUCCESS = 'TOP_ANIME_LIST_SUCCESS';
export const TOP_ANIME_LIST_FAIL = 'TOP_ANIME_LIST_FAIL';

export const TOP_ANIME_DETAILS_REQUEST = 'TOP_ANIME_DETAILS_REQUEST';
export const TOP_ANIME_DETAILS_SUCCESS = 'TOP_ANIME_DETAILS_SUCCESS';
export const TOP_ANIME_DETAILS_FAIL = 'TOP_ANIME_DETAILS_FAIL';

export const TOP_ANIME_DELETE_REQUEST = 'TOP_ANIME_DELETE_REQUEST';
export const TOP_ANIME_DELETE_SUCCESS = 'TOP_ANIME_DELETE_SUCCESS';
export const TOP_ANIME_DELETE_FAIL = 'TOP_ANIME_DELETE_FAIL';

export const TOP_ANIME_CREATE_REQUEST = 'TOP_ANIME_CREATE_REQUEST';
export const TOP_ANIME_CREATE_SUCCESS = 'TOP_ANIME_CREATE_SUCCESS';
export const TOP_ANIME_CREATE_FAIL = 'TOP_ANIME_CREATE_FAIL';
export const TOP_ANIME_CREATE_RESET = 'TOP_ANIME_CREATE_RESET';

export const TOP_ANIME_UPDATE_REQUEST = 'TOP_ANIME_UPDATE_REQUEST';
export const TOP_ANIME_UPDATE_SUCCESS = 'TOP_ANIME_UPDATE_SUCCESS';
export const TOP_ANIME_UPDATE_FAIL = 'TOP_ANIME_UPDATE_FAIL';
export const TOP_ANIME_UPDATE_RESET = 'TOP_ANIME_UPDATE_RESET';

export const TOP_ANIME_CREATE_REVIEW_REQUEST = 'TOP_ANIME_CREATE_REVIEW_REQUEST';
export const TOP_ANIME_CREATE_REVIEW_SUCCESS = 'TOP_ANIME_CREATE_REVIEW_SUCCESS';
export const TOP_ANIME_CREATE_REVIEW_FAIL = 'TOP_ANIME_CREATE_REVIEW_FAIL';
export const TOP_ANIME_CREATE_REVIEW_RESET = 'TOP_ANIME_CREATE_REVIEW_RESET';

export const TOP_ANIME_TOP_REQUEST = 'TOP_ANIME_TOP_REQUEST';
export const TOP_ANIME_TOP_SUCCESS = 'TOP_ANIME_TOP_SUCCESS';
export const TOP_ANIME_TOP_FAIL = 'TOP_ANIME_TOP_FAIL';